### ISSUE TITLE
 Missing key pretty

### ISSUE THREAD

**Issue by andorxornot** [CompVis/imagebart#3]
Hi! 

When I tried to generate a sample with lsun checkpoint i got an error:
```
  File "sample_imagebart.py", line 295, in <module>
    print(paths.pretty())
...
omegaconf.errors.ConfigAttributeError: Missing key pretty
    full_key: pretty
    object_type=dict
```

**Comment by ablattmann** [comment]
I think this was due to a version mismatch between the `omegaconf`version we provided in our `environment.yaml` and your actually installed `omegaconf` version. Should be fixed in https://github.com/CompVis/imagebart/commit/c11ea830ebf74dd0f9c1307462c9de24f536a9e7

**Comment by andorxornot** [comment]
thanks!
